import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState, useRef } from 'react'
import styles from '../styles/Home.module.css'
import Form from 'react-bootstrap/Form'
import { Card } from 'react-bootstrap'

export default function Home() {
  const [toDoList, setToDoList] = useState([])
  const [toDoFormValue, setToDoFormValue] = useState('')
  const addTodo = (todoParam) => setToDoList(currentVal => [...currentVal, todoParam])

  useEffect(() => {
    const enterKeyDownHandler = (e) => {
      if (e.keyCode !== 13) {
        return
      }
      setToDoFormValue(currentVal => {
        if (currentVal === '') {
          return currentVal
        }
        addTodo(currentVal)
        return ''
      })
    }

    document.addEventListener('keydown', enterKeyDownHandler)
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Simple To-Do List App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Simple To-Do List App
        </h1>
        <div className='mt-3 mb-3 w-50'>
          <Form.Control size="lg" type="text" placeholder="Add a to-do item" value={ toDoFormValue } onChange={ (e) => setToDoFormValue(e.target.value) }/>
        </div>

        <div className='w-50'>
          {toDoList.map((todo, index) => {
            return (
              <Card key={index} className='mt-3'>
                <Card.Body>
                  <Card.Title>{ todo }</Card.Title>
                </Card.Body>
              </Card>
            )
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
